# Generated by Django 5.0.4 on 2024-07-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="home_team",
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mongo_id", models.CharField(max_length=24, unique=True)),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="core.club",
                    ),
                ),
            ],
        ),
    ]
