# Generated by Django 5.0.4 on 2024-07-02 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_match_home_team_matches"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Match",
        ),
    ]
