# Generated by Django 5.0.4 on 2024-07-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mongo_id", models.CharField(max_length=24, unique=True)),
                ("competition", models.CharField(max_length=255)),
                ("venue", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Upcoming", "Upcoming"), ("Completed", "Completed")],
                        max_length=50,
                    ),
                ),
                ("attendance", models.IntegerField()),
                ("referee", models.CharField(max_length=255)),
                ("season", models.CharField(max_length=50)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="core.club",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="core.club",
                    ),
                ),
                (
                    "win_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="win_matches",
                        to="core.club",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Matches",
        ),
    ]
