# Generated by Django 5.0.4 on 2024-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_match_win_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="win_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home_team", "Home Tesam"),
                    ("away_team", "Away Team"),
                    ("draw", "Draw"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
