# Generated by Django 5.0.4 on 2024-07-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_match_win_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="win_team",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
