# Generated by Django 5.0.4 on 2024-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_match_win_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name": "Match", "verbose_name_plural": "Matches"},
        ),
    ]
