# Generated by Django 5.0.4 on 2024-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={},
        ),
    ]
