# Generated by Django 5.0.4 on 2024-07-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_match_win_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="win_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="win_matches",
                to="core.club",
            ),
        ),
    ]
