# Generated by Django 5.0.4 on 2024-07-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_match_win_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="win_team",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("id", models.F("home_matches")),
                    ("id", models.F("away_matches")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="win_matches",
                to="core.club",
            ),
        ),
    ]
